[config]
schemaVersion = "0.0.1"

[package]
namespace = "Sparroh"
name = "ModSettingsMenu"
description = "Adapted from ToeKneeRED's 'MycoModList'. Allows editing of mod config files within the game."
websiteUrl = "https://github.com/Little-Sparroh/ModSettingsMenu"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Mycopunk = "5.4.2403"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "bin/Release/net48/ModSettingsMenu.dll"
target = "BepInEx/plugins/ModSettingsMenu.dll"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE"
target = "LICENSE"

[publish]
repository = "https://thunderstore.io"
communities = [ "mycopunk" ]

[publish.categories]
mycopunk = [ "client" ]


